dj_deploy/app/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', ModeloView.as_view(), name="modelo_list"),
    path('new', ModeloNew.as_view(), name="new"),
    path('edit/<int:pk>', ModeloEdit.as_view(), name="edit"),
]

dj_deploy/dj_deploy/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include(('app.urls', 'app'), namespace='app')),
    path('admin/', admin.site.urls),
]

dj_deploy/app/models.py
from django.db import models

class Modelo(models.Model):
    codigo = models.CharField("Codigo", max_length=10, unique=True)
    descripciion = models.CharField(max_length=255)

    def __str__(self):
        return self.codigo

    class Meta:
        verbose_name_plural = "Modelos"

dj_deploy/app/forms.py
from django import forms

from .models import *

class ModeloForm(forms.ModelForm):
    class Meta:
        model= Modelo
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            }) 

dj_deploy/app/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy

from .models import *
from .forms import *

class ModeloView(generic.ListView):
    permission_required = "app.view_modelo"
    model = Modelo
    template_name = "app/modelo_list.html"
    context_object_name = "obj"

class ModeloNew(generic.CreateView):
    permission_required="app.add_modelo"
    model=Modelo
    template_name="app/modelo_form.html"
    context_object_name = "obj"
    form_class=ModeloForm
    success_url=reverse_lazy("app:modelo_list")
    

class ModeloEdit(generic.UpdateView):
    permission_required="app.change_modelo"
    model=Modelo
    template_name="app/modelo_form.html"
    context_object_name = "obj"
    form_class=ModeloForm
    success_url=reverse_lazy("app:modelo_list")
    success_message="Modelo Actualizado Satisfactoriamente"

    def form_valid(self, form):
        form.instance.um = self.request.user.id
        return super().form_valid(form)

class ModeloDel(generic.DeleteView):
    permission_required="app.delete_modelo"
    model=Modelo
    template_name='app/catalogos_del.html'
    context_object_name='obj'
    success_url=reverse_lazy("app:modelo_list")
    success_message="Modelo Eliminado Satisfactoriamente"

dj_deploy/app/templates/app/modelo_form.html
{% extends 'bases/index.html' %}

{% block content %}
<form method="post">
    <fieldset>
        <legend>
            {% if not obj %}Nuevo{%else%}Editar{% endif%}
        </legend>
        {%csrf_token%}
        {{form}}

        <button type="submit" class="btn btn-primary">Guardar</button>
    </fieldset>
</form>
{% endblock %}

dj_deploy/app/templates/app/modelo_list.html
{% extends 'bases/index.html' %}

{% block content %}
<table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">Id</th>
        <th scope="col">Código</th>
        <th scope="col">Descripción</th>
        <th scope="col">Acción</th>
      </tr>
    </thead>
    <tbody>
    {% for item in obj %}
      <tr>
          <td>{{item.id}}</td>
          <td>{{item.codigo}}</td>
          <td>{{item.descripciion}}</td>
          <td>
            <a href="{% url 'app:edit' item.id %}" class="btn btn-block btn-info">Editar</a>
          </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock%}

dj_deploy/templates/bases/index.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Proyecto Para Hacer Deploy</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
    <div class="alert alert-dismissible alert-warning">
        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        <h4 class="alert-heading">Atención</h4>
        <p class="mb-0">Este proyecto forma parte del curso Deploy de Django , elaborado por Alfredo salas, <a href="" target="_blank" class="alert-link">Síguenos</a>.</p>
      </div>

    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Deploy DJ</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
      
          <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav me-auto">
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'app:modelo_list' %}">Lista
                    <span class="visually-hidden">(current)</span>
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'app:new' %}">Nuevo</a>
                </li>
              </ul>
          </div>
        </div>
      </nav>
      <div class="container-fluid">
        <div class="row">
          {% block content%}
          {% endblock %}
        </div>
      </div>
</body>
</html>